
package paneles;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logico.Iterator_Provee;
import logico.Manager_Provee;
import logico.Manager_Proveedor;
import logico.Provee;
import logico.Proveedor;
import logico.Renglon_Compra;

public class Agregar_Producto extends javax.swing.JPanel {
    
    private Manager_Provee manager_provee;
    private Renglon_Compra renglon;
    private DefaultTableModel modelo;
    public Agregar_Producto(String proveedor) throws Exception {
        initComponents();
        manager_provee = Manager_Provee.getInstance();
        modelo = (DefaultTableModel) materia.getModel();
        
        proveedor_lista.addItem("Nombre Proveedor");
        if (!"".equals(proveedor)){
            proveedor_lista.addItem(proveedor);
            proveedor_lista.setSelectedIndex(1);
            proveedor_lista.setEnabled(false);
            
        }
        else{
            Titulo.setText("CONSULTAR MATERIA PRIMA DE LOS PROVEEDORES");
            volver.setVisible(false);
            cantidad_ingresar.setVisible(false);
            requerida.setVisible(false);
            seleccionar.setVisible(false);
            cantidadtext.setVisible(false);
            confirmar.setVisible(false);
            
            Manager_Proveedor manager_proveedor = Manager_Proveedor.getInstance();

            ArrayList<Proveedor> proveedores = manager_proveedor.getAllProveedores();
            String auxiliar;


            for (int i = 0; i<proveedores.size(); i++){
                auxiliar = proveedores.get(i).getNombre();
                proveedor_lista.addItem(auxiliar);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Separador6 = new javax.swing.JLabel();
        proveedor_lista = new javax.swing.JComboBox<>();
        buscar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombre_materiaprima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cantidad_ingresar = new javax.swing.JTextField();
        cantidadtext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        materia = new javax.swing.JTable();
        requerida = new javax.swing.JLabel();
        seleccionar = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        contenedor.setBackground(new java.awt.Color(204, 204, 204));
        contenedor.setMaximumSize(new java.awt.Dimension(1042, 619));
        contenedor.setLayout(new java.awt.CardLayout());

        inicio.setBackground(new java.awt.Color(227, 227, 218));
        inicio.setMaximumSize(new java.awt.Dimension(1042, 619));
        inicio.setPreferredSize(new java.awt.Dimension(1042, 619));

        Titulo.setFont(new java.awt.Font("Microsoft YaHei", 1, 21)); // NOI18N
        Titulo.setForeground(new java.awt.Color(97, 34, 34));
        Titulo.setText("MATERIA PRIMA");

        Separador6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Separador6.setForeground(new java.awt.Color(97, 34, 34));
        Separador6.setText("__________________________________________________________________________________________________________________________________________________________________________________________________");

        proveedor_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedor_listaActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre  materia prima:");

        nombre_materiaprima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_materiaprimaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Proveedor");

        cantidad_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad_ingresarActionPerformed(evt);
            }
        });

        cantidadtext.setForeground(new java.awt.Color(0, 0, 0));
        cantidadtext.setText("Cantidad requerida:");

        materia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Productor", "Nombre del Producto", "Precio de Unidad"
            }
        ));
        jScrollPane1.setViewportView(materia);

        requerida.setForeground(new java.awt.Color(51, 51, 51));
        requerida.setText("(*)");

        seleccionar.setForeground(new java.awt.Color(0, 0, 0));
        seleccionar.setText("Seleccione la materia prima que desee comprar");

        volver.setText("Volver a orden de compra");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(seleccionar))
                    .addComponent(Separador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addComponent(volver)
                        .addGap(80, 80, 80)
                        .addComponent(cantidadtext)
                        .addGap(32, 32, 32)
                        .addComponent(cantidad_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(requerida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inicioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(proveedor_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nombre_materiaprima, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Titulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Separador6)
                        .addGap(18, 18, 18)
                        .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proveedor_lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_materiaprima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(seleccionar)
                .addGap(8, 8, 8)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadtext)
                    .addComponent(requerida)
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 28));

        contenedor.add(inicio, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cantidad_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad_ingresarActionPerformed

    private void nombre_materiaprimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_materiaprimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_materiaprimaActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed

        if (materia.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this,"Debe seleccionar un renglon","", JOptionPane.WARNING_MESSAGE);
            seleccionar.setForeground(Color.RED);
            return;
        }
        
        try{
            if (Integer.parseInt(cantidad_ingresar.getText())<=0){
                JOptionPane.showMessageDialog(this,"Debe ingresar una cantidad valida, mayor a 0","", JOptionPane.WARNING_MESSAGE);
                requerida.setForeground(Color.red);
                return;
            }
        }catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Debe ingresar valores validos de cantidad","", JOptionPane.WARNING_MESSAGE);
                requerida.setForeground(Color.red);
                return;
        }
        

        renglon = new Renglon_Compra();
        renglon.setNombre_Tiene((materia.getValueAt(materia.getSelectedRow() , 1).toString()));
        renglon.setCantidad(Integer.parseInt(cantidad_ingresar.getText()));
        renglon.setPrecio(getRenglon().getCantidad()*(double)materia.getValueAt(materia.getSelectedRow() , 2));

        paneles.Principal.getNeophos().go_to(paneles.Principal.getGenerar_Orden());
    }//GEN-LAST:event_confirmarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        modelo.setRowCount(0);
        if(proveedor_lista.getSelectedIndex() == 0 && nombre_materiaprima.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Debe seleccionar un proveedor o ingresar un id","", JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        

        String proveedor = proveedor_lista.getSelectedItem().toString();
        String nombre_Materia = nombre_materiaprima.getText();;

        Provee materia_consultada;
        
        if(proveedor_lista.getSelectedIndex() != 0 && !nombre_materiaprima.getText().isBlank()){
            try {
                materia_consultada = manager_provee.consultar_todos(proveedor, nombre_Materia);
                if (materia_consultada.getNombre_Producto() == ""){
                    no_hay_valores();
                    return;
                }
                modelo.addRow(new Object[] {materia_consultada.getNombre_Proveedor(), materia_consultada.getNombre_Producto(), materia_consultada.getPrecio()});
            } catch (Exception ex) {
                Logger.getLogger(Agregar_Producto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (proveedor_lista.getSelectedIndex() != 0){
            try {
                Iterator_Provee iterator = new Iterator_Provee(manager_provee.buscar_Materias_porProveedor(proveedor));
                if (!iterator.hayMas()){
                    no_hay_valores();
                    return;
                }
                while(iterator.hayMas()){
                    materia_consultada = iterator.siguiente();
                    modelo.addRow(new Object[] {materia_consultada.getNombre_Proveedor(), materia_consultada.getNombre_Producto(), materia_consultada.getPrecio()});
                }
            } catch (Exception ex) {
                Logger.getLogger(Agregar_Producto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (!nombre_materiaprima.getText().isBlank()){
            try {
                Iterator_Provee iterator = new Iterator_Provee(manager_provee.buscar_Materias_porMateria(nombre_Materia));
                if (!iterator.hayMas()){
                    no_hay_valores();
                    return;
                }

                while(iterator.hayMas()){
                    materia_consultada = iterator.siguiente();
                    modelo.addRow(new Object[] {materia_consultada.getNombre_Proveedor(), materia_consultada.getNombre_Producto(), materia_consultada.getPrecio()});
                }
            } catch (Exception ex) {
                Logger.getLogger(Agregar_Producto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (modelo.getRowCount()==0){
            no_hay_valores();
        }
    }//GEN-LAST:event_buscarActionPerformed

    public void no_hay_valores(){
        JOptionPane.showMessageDialog(this,"No hay resultados disponibles para la busqueda realizada","", JOptionPane.WARNING_MESSAGE);
        nombre_materiaprima.setText("");
        if (proveedor_lista.isEnabled()) proveedor_lista.setSelectedIndex(0);
        
        return;
    }
    
    private void proveedor_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedor_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedor_listaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        int input = JOptionPane.showConfirmDialog(this,"Seguro desea volver a la pantalla orden de compra?", "¡Cuidado!",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == 0){
            renglon = null;
            paneles.Principal.getNeophos().go_to(paneles.Principal.getGenerar_Orden());
        }
    }//GEN-LAST:event_volverActionPerformed

    public Renglon_Compra getRenglon(){
        return this.renglon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Separador6;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cantidad_ingresar;
    private javax.swing.JLabel cantidadtext;
    private javax.swing.JButton confirmar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable materia;
    private javax.swing.JTextField nombre_materiaprima;
    private javax.swing.JComboBox<String> proveedor_lista;
    private javax.swing.JLabel requerida;
    private javax.swing.JLabel seleccionar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

}
