/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logico.IteradorOrdenProduccion;
import logico.IteradorRenglonProduccion;
import logico.ManagerOrdenProduccion;
import logico.OrdenProduccion;
import logico.RenglonProduccion;

/**
 *
 * @author Usuario
 */
public class Consultar_OrdenDeProduccion extends javax.swing.JPanel {
    private ManagerOrdenProduccion manager;
    private DefaultTableModel modelo;
    private DefaultTableModel modelo2;
    public List<OrdenProduccion> ordenes = new ArrayList<>();
    private OrdenProduccion orden = new OrdenProduccion();
   
    public Consultar_OrdenDeProduccion() throws Exception {
        initComponents();
       
        modelo = (DefaultTableModel) tablaInicio1.getModel();
       
        modelo2 = (DefaultTableModel) tablaRenglones1.getModel();
       
        ordenes = manager.consultarTodasLasOrdenes();
       
        IteradorOrdenProduccion iterador = new IteradorOrdenProduccion(ordenes);
       
        if(ordenes.get(1).getPrecioTotal() == 0){
            JOptionPane.showMessageDialog(this,"No hay ordenes de producción en la base de datos.","", JOptionPane.WARNING_MESSAGE);
        }else{
            while(iterador.hayMas()){
                orden = iterador.siguiente();
                modelo.addRow(new Object[]{orden.getFechaPedido(), orden.getFecha_limite(), orden.getPrecioTotal()});
            }
        }
    }
  
       

    public void reiniciar(){
        fechaPText.setText("");
        fechaLimiteText.setText("");
        fechaRealizacionText.setText("");
        precioTotalText.setText("");
        modelo2.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        inicioOP = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        Separador7 = new javax.swing.JLabel();
        aceptarButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInicio1 = new javax.swing.JTable();
        mesas1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mesas = new javax.swing.JLabel();
        muestraOP = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        Separador8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaRenglones1 = new javax.swing.JTable();
        volverButton2 = new javax.swing.JButton();
        infoOrdenLabel1 = new javax.swing.JLabel();
        FechaPLabel1 = new javax.swing.JLabel();
        fechaLimiteLabel = new javax.swing.JLabel();
        infoRenglonesLabel1 = new javax.swing.JLabel();
        fechaPText = new javax.swing.JLabel();
        fechaLimiteText = new javax.swing.JLabel();
        precioTotalText = new javax.swing.JLabel();
        mesas2 = new javax.swing.JLabel();
        recetaLabel = new javax.swing.JLabel();
        precioTotalLabel = new javax.swing.JLabel();
        fechaRealizacionText = new javax.swing.JLabel();
        fechaRealizacionLabel = new javax.swing.JLabel();
        recetaText1 = new javax.swing.JLabel();

        contenedor.setBackground(new java.awt.Color(204, 204, 204));
        contenedor.setMaximumSize(new java.awt.Dimension(1042, 619));
        contenedor.setLayout(new java.awt.CardLayout());

        inicioOP.setBackground(new java.awt.Color(227, 227, 218));
        inicioOP.setMaximumSize(new java.awt.Dimension(1042, 619));
        inicioOP.setPreferredSize(new java.awt.Dimension(1065, 619));

        Titulo1.setFont(new java.awt.Font("Microsoft YaHei", 1, 21)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(97, 34, 34));
        Titulo1.setText("CONSULTAR ORDEN DE PRODUCCIÓN");

        Separador7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Separador7.setForeground(new java.awt.Color(97, 34, 34));
        Separador7.setText("__________________________________________________________________________________________________________________________________________________________________________________________________");

        aceptarButton1.setBackground(new java.awt.Color(117, 49, 49));
        aceptarButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        aceptarButton1.setForeground(new java.awt.Color(255, 255, 255));
        aceptarButton1.setText("ACEPTAR");
        aceptarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButton1ActionPerformed(evt);
            }
        });

        tablaInicio1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        tablaInicio1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Pedido", "Fecha Limite", "Precio Total"
            }
        ));
        tablaInicio1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaInicio1);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 2, 12)); // NOI18N
        jLabel3.setText("Seleccione la orden de producción que desea consultar");

        mesas.setText("              ");

        javax.swing.GroupLayout inicioOPLayout = new javax.swing.GroupLayout(inicioOP);
        inicioOP.setLayout(inicioOPLayout);
        inicioOPLayout.setHorizontalGroup(
            inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioOPLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioOPLayout.createSequentialGroup()
                        .addGroup(inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inicioOPLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Titulo1)
                                .addGap(188, 188, 188)
                                .addComponent(mesas))
                            .addComponent(Separador7))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioOPLayout.createSequentialGroup()
                        .addGroup(inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(inicioOPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aceptarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesas1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        inicioOPLayout.setVerticalGroup(
            inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioOPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo1)
                    .addComponent(mesas))
                .addGap(1, 1, 1)
                .addComponent(Separador7)
                .addGroup(inicioOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inicioOPLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(mesas1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inicioOPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(aceptarButton1)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        mesas.setFont(new java.awt.Font("DialogInput", 1, 28));

        contenedor.add(inicioOP, "card2");

        muestraOP.setBackground(new java.awt.Color(227, 227, 218));
        muestraOP.setMaximumSize(new java.awt.Dimension(1042, 619));
        muestraOP.setPreferredSize(new java.awt.Dimension(1065, 619));

        Titulo2.setFont(new java.awt.Font("Microsoft YaHei", 1, 21)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(97, 34, 34));
        Titulo2.setText("CONSULTAR ORDEN DE PRODUCCIÓN");

        Separador8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Separador8.setForeground(new java.awt.Color(97, 34, 34));
        Separador8.setText("__________________________________________________________________________________________________________________________________________________________________________________________________");

        tablaRenglones1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        tablaRenglones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Precio ", "Producto que tiene"
            }
        ));
        tablaRenglones1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaRenglones1);

        volverButton2.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        volverButton2.setText("VOLVER");
        volverButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton2ActionPerformed(evt);
            }
        });

        infoOrdenLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        infoOrdenLabel1.setForeground(new java.awt.Color(97, 34, 34));
        infoOrdenLabel1.setText("Información de la Orden de Producción consultada:");

        FechaPLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        FechaPLabel1.setForeground(new java.awt.Color(97, 34, 34));
        FechaPLabel1.setText("Fecha Pedido:");

        fechaLimiteLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        fechaLimiteLabel.setForeground(new java.awt.Color(97, 34, 34));
        fechaLimiteLabel.setText("Fecha Limite:");

        infoRenglonesLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        infoRenglonesLabel1.setForeground(new java.awt.Color(97, 34, 34));
        infoRenglonesLabel1.setText("Información de su/s renglon/es:");

        recetaLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        recetaLabel.setForeground(new java.awt.Color(97, 34, 34));
        recetaLabel.setText("Receta:");

        precioTotalLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        precioTotalLabel.setForeground(new java.awt.Color(97, 34, 34));
        precioTotalLabel.setText("Precio Total:");

        fechaRealizacionLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        fechaRealizacionLabel.setForeground(new java.awt.Color(97, 34, 34));
        fechaRealizacionLabel.setText("Fecha Realizacion:");

        javax.swing.GroupLayout muestraOPLayout = new javax.swing.GroupLayout(muestraOP);
        muestraOP.setLayout(muestraOPLayout);
        muestraOPLayout.setHorizontalGroup(
            muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(muestraOPLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(muestraOPLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Titulo2))
                    .addComponent(Separador8)
                    .addGroup(muestraOPLayout.createSequentialGroup()
                        .addGap(0, 1047, Short.MAX_VALUE)
                        .addComponent(mesas2)))
                .addGap(58, 58, 58))
            .addGroup(muestraOPLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoOrdenLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(muestraOPLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(muestraOPLayout.createSequentialGroup()
                                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechaLimiteLabel)
                                    .addComponent(FechaPLabel1)
                                    .addComponent(recetaLabel)
                                    .addComponent(precioTotalLabel)
                                    .addComponent(fechaRealizacionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaPText, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(fechaLimiteText, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(precioTotalText, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(fechaRealizacionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(recetaText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(81, 81, 81)
                                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoRenglonesLabel1)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(muestraOPLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(volverButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        muestraOPLayout.setVerticalGroup(
            muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(muestraOPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Titulo2)
                .addGap(1, 1, 1)
                .addComponent(Separador8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoOrdenLabel1)
                .addGap(14, 14, 14)
                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesas2)
                    .addGroup(muestraOPLayout.createSequentialGroup()
                        .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaPText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaPLabel1)
                            .addComponent(infoRenglonesLabel1))
                        .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(muestraOPLayout.createSequentialGroup()
                                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(muestraOPLayout.createSequentialGroup()
                                        .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(muestraOPLayout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(fechaLimiteLabel))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, muestraOPLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fechaLimiteText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42)
                                        .addComponent(fechaRealizacionLabel))
                                    .addGroup(muestraOPLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaRealizacionText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(recetaLabel)
                                    .addComponent(recetaText1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(muestraOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(precioTotalLabel)
                                    .addComponent(precioTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(muestraOPLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29)
                .addComponent(volverButton2)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        mesas.setFont(new java.awt.Font("DialogInput", 1, 28));

        contenedor.add(muestraOP, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1134, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButton1ActionPerformed

        Map<OrdenProduccion, List<RenglonProduccion>> ordenCompleta = new HashMap<>();
        OrdenProduccion infoOrden = new OrdenProduccion();
        List<RenglonProduccion> infoRenglones = new ArrayList<RenglonProduccion>();
        RenglonProduccion info = new RenglonProduccion();

        if (tablaInicio1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Debe seleccionar un renglon","", JOptionPane.WARNING_MESSAGE);
            return;
        }else{

            orden = ordenes.get(tablaInicio1.getSelectedRow());
            int id = orden.getId();

            try {
                ordenCompleta = manager.consultarOrdenDeProduccion(id);
                        
                Set<OrdenProduccion> keys = ordenCompleta.keySet();
                for(OrdenProduccion key : keys){
                    infoOrden = key;
                }

                infoRenglones = ordenCompleta.get(infoOrden);
                IteradorRenglonProduccion iterador = new IteradorRenglonProduccion(infoRenglones);

                inicioOP.setVisible(false);
                muestraOP.setVisible(true);

                fechaPText.setText(infoOrden.getFechaPedido().toString());
                fechaLimiteText.setText(infoOrden.getFecha_limite().toString());
                fechaRealizacionText.setText("Pendiente");
                fechaRealizacionText.setText(infoOrden.getReceta());
                precioTotalText.setText(String.valueOf(infoOrden.getPrecioTotal()));

                while(iterador.hayMas()){
                    info = iterador.siguiente();
                    modelo2.addRow(new Object[] {info.getCantidad(), info.getPrecio(), info.getNombre_Tiene()});
                }

            } catch (Exception ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Sucedió un error inesperado.\n");
            }
        }
    }//GEN-LAST:event_aceptarButton1ActionPerformed

    private void volverButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton2ActionPerformed
        muestraOP.setVisible(false);
        reiniciar();
    }//GEN-LAST:event_volverButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaPLabel1;
    private javax.swing.JLabel Separador7;
    private javax.swing.JLabel Separador8;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JButton aceptarButton1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel fechaLimiteLabel;
    private javax.swing.JLabel fechaLimiteText;
    private javax.swing.JLabel fechaPText;
    private javax.swing.JLabel fechaRealizacionLabel;
    private javax.swing.JLabel fechaRealizacionText;
    private javax.swing.JLabel infoOrdenLabel1;
    private javax.swing.JLabel infoRenglonesLabel1;
    private javax.swing.JPanel inicioOP;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mesas;
    private javax.swing.JLabel mesas1;
    private javax.swing.JLabel mesas2;
    private javax.swing.JPanel muestraOP;
    private javax.swing.JLabel precioTotalLabel;
    private javax.swing.JLabel precioTotalText;
    private javax.swing.JLabel recetaLabel;
    private javax.swing.JLabel recetaText1;
    private javax.swing.JTable tablaInicio1;
    private javax.swing.JTable tablaRenglones1;
    private javax.swing.JButton volverButton2;
    // End of variables declaration//GEN-END:variables
}
