
package paneles;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logico.Manager_Provee;
import logico.Manager_Proveedor;
import logico.Provee;
import logico.Proveedor;
import logico.Renglon;

public class Consultar_ProductoFinal extends javax.swing.JPanel {
    
    private Manager_Provee manager_provee;
    private Renglon renglon;
    private DefaultTableModel modelo;
    public Consultar_ProductoFinal(String proveedor) throws Exception {
        initComponents();
        manager_provee = Manager_Provee.getInstance();
        modelo = (DefaultTableModel) materia.getModel();
        
        proveedor_lista.addItem("ID Proveedor - Nombre");
        
        if (proveedor != ""){
            proveedor_lista.addItem(proveedor);
            proveedor_lista.setSelectedIndex(1);
            proveedor_lista.setEnabled(false);
            
        }
        else{
            volver.setVisible(false);
            cantidad_ingresar.setVisible(false);
            requerida.setVisible(false);
            seleccionar.setVisible(false);
            cantidadtext.setVisible(false);
            confirmar.setVisible(false);
            
            Manager_Proveedor manager_proveedor = Manager_Proveedor.getInstance();

            ArrayList<Proveedor> proveedores = manager_proveedor.getAllProveedores();
            String auxiliar;
            proveedor_lista.addItem("Nombre Proveedor");


            for (int i = 0; i<proveedores.size(); i++){
                auxiliar = proveedores.get(i).getNombre();
                proveedor_lista.addItem(auxiliar);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Separador6 = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cantidad_ingresar = new javax.swing.JTextField();
        cantidadtext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        materia = new javax.swing.JTable();
        requerida = new javax.swing.JLabel();
        seleccionar = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        contenedor.setBackground(new java.awt.Color(204, 204, 204));
        contenedor.setMaximumSize(new java.awt.Dimension(1042, 619));
        contenedor.setLayout(new java.awt.CardLayout());

        inicio.setBackground(new java.awt.Color(227, 227, 218));
        inicio.setMaximumSize(new java.awt.Dimension(1042, 619));
        inicio.setPreferredSize(new java.awt.Dimension(1042, 619));

        Titulo.setFont(new java.awt.Font("Microsoft YaHei", 1, 21)); // NOI18N
        Titulo.setForeground(new java.awt.Color(97, 34, 34));
        Titulo.setText("CONSULTAR PRODUCTO FINAL");

        Separador6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Separador6.setForeground(new java.awt.Color(97, 34, 34));
        Separador6.setText("__________________________________________________________________________________________________________________________________________________________________________________________________");

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        cantidad_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad_ingresarActionPerformed(evt);
            }
        });

        cantidadtext.setForeground(new java.awt.Color(0, 0, 0));
        cantidadtext.setText("Cantidad requerida:");

        materia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Productor", "Nombre del Producto", "Precio de Unidad"
            }
        ));
        jScrollPane1.setViewportView(materia);

        requerida.setForeground(new java.awt.Color(51, 51, 51));
        requerida.setText("(*)");

        seleccionar.setForeground(new java.awt.Color(0, 0, 0));
        seleccionar.setText("Seleccione la materia prima que desee comprar");

        volver.setText("Volver a orden de compra");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(seleccionar))
                    .addComponent(Separador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addComponent(volver)
                        .addGap(80, 80, 80)
                        .addComponent(cantidadtext)
                        .addGap(32, 32, 32)
                        .addComponent(cantidad_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(requerida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inicioLayout.createSequentialGroup()
                                .addGap(822, 822, 822)
                                .addComponent(jLabel1))
                            .addComponent(Titulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Separador6)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(seleccionar)
                .addGap(8, 8, 8)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadtext)
                    .addComponent(requerida)
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 28));

        contenedor.add(inicio, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        int input = JOptionPane.showConfirmDialog(this,"Seguro desea volver a la pantalla orden de compra?", "¡Cuidado!",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == 0){
            renglon = null;
            paneles.Principal.getNeophos().go_to(paneles.Principal.getGenerar_Orden());
        }
    }//GEN-LAST:event_volverActionPerformed

    private void cantidad_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad_ingresarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed

        if (materia.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this,"Debe seleccionar un renglon","", JOptionPane.WARNING_MESSAGE);
            seleccionar.setForeground(Color.RED);
            return;
        }

        try{
            if (Integer.parseInt(cantidad_ingresar.getText())<=0){
                JOptionPane.showMessageDialog(this,"Debe ingresar una cantidad valida, mayor a 0","", JOptionPane.WARNING_MESSAGE);
                requerida.setForeground(Color.red);
                return;
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Debe ingresar valores validos de cantidad","", JOptionPane.WARNING_MESSAGE);
            requerida.setForeground(Color.red);
            return;
        }

        renglon = new Renglon();
        renglon.setNombre_Tiene((materia.getValueAt(materia.getSelectedRow() , 1).toString()));
        renglon.setCantidad(Integer.parseInt(cantidad_ingresar.getText()));
        renglon.setPrecio(getRenglon().getCantidad()*(double)materia.getValueAt(materia.getSelectedRow() , 2));

        paneles.Principal.getNeophos().go_to(paneles.Principal.getGenerar_Orden());
    }//GEN-LAST:event_confirmarActionPerformed

    public void no_hay_valores(){
        JOptionPane.showMessageDialog(this,"No hay resultados disponibles para la busqueda realizada","", JOptionPane.WARNING_MESSAGE);
        nombre_materiaprima.setText("");
        if (proveedor_lista.isEnabled()) proveedor_lista.setSelectedIndex(0);
        return;
    }
    
    public Renglon getRenglon(){
        return this.renglon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Separador6;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField cantidad_ingresar;
    private javax.swing.JLabel cantidadtext;
    private javax.swing.JButton confirmar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable materia;
    private javax.swing.JLabel requerida;
    private javax.swing.JLabel seleccionar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

}
